spring.application.name=academy-spring-boot-mvc

# TODO #2 thymeleaf, mustache 설정 추가
spring.thymeleaf.prefix=classpath:/templates/thymeleaf/
spring.thymeleaf.suffix=.html

spring.mustache.prefix=classpath:/templates/mustache/
spring.mustache.suffix=.mustache

spring.thymeleaf.cache=false