spring.application.name=academy-spring-boot-mvc


# TODO #1: multipart config
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.servlet.multipart.location=/tmp
spring.servlet.multipart.file-size-threshold=1024
